#!/system/bin/sh

#sets stune variables

echo "5" > /dev/stune/background/schedtune.boost

echo "1" > /dev/stune/background/schedtune.prefer_idle


echo "15" > /dev/stune/foreground/schedtune.boost

echo "1" > /dev/stune/foreground/schedtune.prefer_idle

echo "0" > /dev/stune/foreground/schedtune.prefer_perf


echo "100" > /dev/stune/rt/schedtune.boost

echo "0" > /dev/stune/rt/schedtune.prefer_idle


echo "100" > /dev/stune/top-app/schedtune.boost

echo "1" > /dev/stune/top-app/schedtune.prefer_idle

echo "0" > /dev/stune/top-app/schedtune.prefer_perf
echo "0-7" > /dev/stune/top-app/cpus


echo "0" > /dev/stune/schedtune.boost

echo "1" > /dev/stune/schedtune.prefer_idle

echo "0" > /dev/stune/schedtune.prefer_perf

#sets cores to workload

echo "0-3" > /dev/cpuset/system-background/cpus

echo "0-3" > /dev/cpuset/background/cpus

echo "0-7" > /dev/cpuset/foreground/cpus

echo "0-7" > /dev/cpuset/top-app/cpus

echo "0-7" > /dev/cpuset/cpus

echo "0-7" > /dev/cpuset/restricted/cpus


#Change Load_balance to 1 on boot

echo "1" > /dev/cpuset/sched_load_balance
echo "1" > /dev/cpuset/system-background/sched_load_balance
echo "1" > /dev/cpuset/background/sched_load_balance
echo "1" > /dev/cpuset/foreground/sched_load_balance
echo "1" > /dev/cpuset/top-app/sched_load_balance
echo "1" > /dev/cpuset/restricted/sched_load_balance

#by iSonik
